version: 2
registries:
  npm-registry-npm-pkg-github-com-navikt-data-catalog-components:
    type: npm-registry
    url: https://npm.pkg.github.com/@navikt/data-catalog-components
    token: "${{secrets.NPM_REGISTRY_NPM_PKG_GITHUB_COM_NAVIKT_DATA_CATALOG_COMPONENTS_TOKEN}}"
  npm-registry-npm-pkg-github-com-deetly-plotly-view:
    type: npm-registry
    url: https://npm.pkg.github.com/@deetly/plotly-view
    token: "${{secrets.NPM_REGISTRY_NPM_PKG_GITHUB_COM_DEETLY_PLOTLY_VIEW_TOKEN}}"

updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: graphql-typescript-definitions
    versions:
    - 0.24.0
    - 0.24.1
  - dependency-name: gatsby-image
    versions:
    - 2.10.0
    - 2.11.0
    - 3.0.0
    - 3.1.0
    - 3.2.0
    - 3.3.0
  - dependency-name: babel-preset-gatsby
    versions:
    - 0.11.0
    - 0.12.0
    - 0.12.1
    - 0.12.2
    - 1.0.0
    - 1.1.0
    - 1.2.0
    - 1.3.0
  - dependency-name: gatsby-react-router-scroll
    versions:
    - 4.3.0
  - dependency-name: eslint
    versions:
    - 7.24.0
  - dependency-name: gatsby
    versions:
    - 2.31.1
    - 2.32.0
    - 2.32.11
    - 2.32.12
    - 2.32.2
    - 2.32.3
    - 2.32.4
    - 2.32.8
    - 2.32.9
  - dependency-name: nav-frontend-ekspanderbartpanel
    versions:
    - 3.0.46
    - 3.1.1
  - dependency-name: nav-frontend-alertstriper
    versions:
    - 3.0.39
    - 3.1.1
  - dependency-name: gatsby-plugin-typescript
    versions:
    - 2.11.0
    - 2.12.0
    - 2.12.1
  - dependency-name: "@types/jest"
    versions:
    - 26.0.20
    - 26.0.21
    - 26.0.22
  - dependency-name: gatsby-plugin-react-helmet
    versions:
    - 3.10.0
    - 3.9.0
  - dependency-name: gatsby-plugin-less
    versions:
    - 4.6.0
    - 4.7.0
  - dependency-name: less
    versions:
    - 4.1.0
    - 4.1.1
  registries:
  - npm-registry-npm-pkg-github-com-navikt-data-catalog-components
  - npm-registry-npm-pkg-github-com-deetly-plotly-view
