apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
    name: sykdom-i-familien
    namespace: dusseldorf
    metadata:
        annotations:
            nais.io/read-only-file-system: "false"
            nais.io/run-as-user: "1001"
            nais.io/run-as-group: "1002"
    labels:
        team: dusseldorf
spec:
    image: {{ image }}
    port: 8080
    liveness:
        path: /isalive.txt
        initialDelay: 3
        timeout: 1
        periodSeconds: 5
        failureThreshold: 10
    readiness:
        path: /isready.txt
        initialDelay: 20
        timeout: 1
    resources:
        limits:
            cpu: 2000m
            memory: 512Mi
        requests:
            cpu: 50m
            memory: 128Mi
    accessPolicy:
        outbound:
            external:
            - host: www.nav.no
            - host: sanity.io
    ingresses:
      {{#each ingresses as |url|}}
       - {{url}}
          {{/each}}
    replicas:
        min: 1
        max: 1
        cpuThresholdPercentage: 90
    prometheus:
        enabled: true
        path: /metrics
    vault:
        enabled: false
    env:
  {{#each env}}
     - name: {{@key}}
       value: "{{this}}"
    {{/each}}
