export const decoratorFragments = {
  NAV_SCRIPTS:
    '<script id="navnoScr" loginurl="https://tjenester.nav.no/dittnav/oversikt" logouturl="https://loginservice.nav.no/slo" authserviceurl="https://tjenester.nav.no/innloggingslinje-api/auth" src="https://appres.nav.no/_public/beta.nav.no/built-navno/js/navno/navno-url.js?_ts=165c8b6dd00"></script><script src="https://appres.nav.no/_public/appressurser/built-appres-v4/js/innloggingslinjen.min.js?_ts=165c88499d0"></script><script type="text/javascript" id="google-tag-manager-props" innholdsvisningssider="" seksjonssider="" subseksjonssider="" src="https://appres.nav.no/_public/beta.nav.no/built-navno/js/navno/google-tag-manager.js?_ts=1695848b5d0"></script>',
  NAV_STYLES:
    '<link href="https://appres.nav.no/_public/shared/bilder/favicon.ico?_ts=151292348c8" rel="icon" type="image/x-icon"><link href="https://appres.nav.no/_public/shared/bilder/favicon.ico?_ts=151292348c8" rel="shortcut icon" type="image/x-icon"><link href="https://appres.nav.no/_public/appressurser/built-appres-v4/styles/css/app-decorator-v4.css?_ts=16b31863740" rel="stylesheet">',
  NAV_HEADING:
    '<div class="hodefot"><header class="siteheader" role="banner"><div class="site-coltrols-toolbar site-controls-toolbar"><div class="container"><div class="row navbar"><div class="col-md-12"><div class="settings"><ul class="nav"><li id="text-size-accessibility" tabindex="0"><span class="link-btn" aria-label="Hold Ctrl-tasten nede (Cmd-tasten på Mac). Trykk samtidig på + for å forstørre eller - for å forminske.">Skriftstørrelse</span><div class="text-size-tooltip"><p>Hold Ctrl-tasten nede (Cmd-tasten på Mac). Trykk samtidig på + for å forstørre eller - for å forminske.</p><span class="arrow"></span></div></li></ul></div><div class="login-container"><div id="login-details" class="hidden"><span id="name-container"><img id="idporten-ikon-innlogging" alt="Innlogget via ID-porten" src="https://appres.nav.no/_public/beta.nav.no/built-navno/img/navno/gfx/icons/idporten_ikon.png?_ts=164657e6e70"><span id="name"></span></span><div class="logout-tooltip hidden"><a href="javascript:void(0)" class="lukk hidden" aria-label="Lukk informasjon om logg ut"> × </a><p>Du er logget inn på alle offentlige tjenester med ID-porten.</p><p> Husk å <strong>logge ut</strong> når du er ferdig.</p><span class="arrow"></span></div></div><div id="auth-btns"><a id="login" class="hidden knapp mini btn-auth btn-login" href="https://tjenester.nav.no/dittnav/oversikt">Logg inn</a><a id="logout" data-ga="Header" class="hidden btn-auth knapp mini hoved btn-logout" href="https://loginservice.nav.no/slo">Logg ut</a></div><div class="login-tooltip hidden"><p>Logg inn på Ditt NAV</p><span class="arrow"></span></div></div></div></div></div></div><div class="sitelogo sitelogo-large"><div class="container"><a href="https://www.nav.no" title="Hjem" data-ga="Header/Logo"><img src="https://appres.nav.no/_public/beta.nav.no/images/logo.png?_ts=1512923c9b0" alt="NAV-logo"></a></div></div><div class="topnavsection-wrapper"><div class="topnavsection"></div></div><div id="varsler-display" class="varsler-display" aria-expanded="false"></div><div class="sitelogo sitelogo-small"><a href="https://www.nav.no" title="Hjem"><img src="https://appres.nav.no/_public/beta.nav.no/images/logo.png?_ts=1512923c9b0" alt="NAV-logo"></a></div></header></div>',
  NAV_FOOTER: '',
  NAV_MENU_RESOURCES: ''
};
